"""Agent 1 extraction round 1: build entity list and produce masked round-1 artifact.

Surface forms must be literal substrings of source_text.txt. This script verifies
each surface form via `in SRC` and drops any that fails.
"""
import json
from pathlib import Path

SRC = Path("source_text.txt").read_text()

# Raw entity records: (entity_id, entity_text, entity_type, [surface_forms])
raw_entities = [
    # ============ CELL TYPES ============
    ("E001", "medium spiny neurons", "CellType", ["medium spiny neurons", "MSNs", "MSN", "medium-spiny-neuron"]),
    ("E002", "D1-type MSNs", "CellType", ["D1-type\nMSNs", "D1 MSNs", "D1 MSN"]),
    ("E003", "D2-type MSNs", "CellType", ["D2-type MSNs", "D2 MSNs", "D2 MSN"]),
    ("E004", "STRd D1 Striosome", "CellType", ["STRd D1 Striosome"]),
    ("E005", "STRd D1 Matrix", "CellType", ["STRd D1 Matrix"]),
    ("E006", "STRv D1", "CellType", ["STRv D1"]),
    ("E007", "STRd D2 Striosome", "CellType", ["STRd D2 Striosome"]),
    ("E008", "STRd D2 Matrix", "CellType", ["STRd D2 Matrix"]),
    ("E009", "STRv D2", "CellType", ["STRv D2"]),
    ("E010", "STRv D1 NUDAP", "CellType", ["STRv D1 NUDAP"]),
    ("E011", "STR D1D2 Hybrid", "CellType", ["STR D1D2 Hybrid", "D1D2 hybrid MSNs", "D1–D2 hybrid"]),
    ("E012", "STRd D2 Hybrid", "CellType", ["STRd D2 Hybrid"]),
    ("E013", "GPi Shell", "CellType", ["GPi Shell"]),
    ("E014", "GPi Core", "CellType", ["GPi Core"]),
    ("E015", "GPin-BF Cholinergic", "CellType", ["GPin-BF Cholinergic", "GPin-BF Chol"]),
    ("E016", "CN LHX6–GBX1", "CellType", ["CN LHX6–GBX1"]),
    ("E017", "GPe SOX6–CTXND1", "CellType", ["GPe SOX6–CTXND1", "GPe SOX6-CTXND1", "GPe SOX8–CTXND1"]),
    ("E018", "GPe MEIS2–SOX6", "CellType", ["GPe MEIS2–SOX6", "GPe MEIS2-SOX6"]),
    ("E019", "cholinergic interneurons", "CellType", ["cholinergic interneurons", "ChAT+", "choline acetyltransferase-positive"]),
    ("E020", "parvalbumin-positive interneurons", "CellType", ["parvalbumin-positive", "PV+"]),
    ("E021", "somatostatin-positive interneurons", "CellType", ["somatostatin-\npositive", "SST+"]),
    ("E022", "neuropeptide Y/tyrosine hydroxylase-positive interneurons", "CellType", ["neuropeptide Y/tyrosine hydroxylase-positive", "NPY+/TH+"]),
    ("E023", "STR TAC3–PLPP4 interneurons", "CellType", ["STR TAC3–PLPP4", "STR TAC3-PLPP4", "TAC3–PLPP4", "TAC3-PLPP4", "STR TAC3"]),
    ("E024", "VIP+ interneurons", "CellType", ["VIP+", "VIP GABA"]),
    ("E025", "LAMP5+ interneurons", "CellType", ["LAMP5+", "LAMP5-CXCL14", "LAMP5–CXCL14"]),
    ("E026", "LAMP5-LHX6", "CellType", ["LAMP5-LHX6"]),
    ("E027", "STR LYPD6-RSPO2", "CellType", ["STR LYPD6-RSPO2"]),
    ("E028", "STR SST-RSPO2", "CellType", ["STR SST-RSPO2"]),
    ("E029", "STR SST-ADARB2", "CellType", ["STR SST-ADARB2", "SST–\nADARB2"]),
    ("E030", "STR SST-CHODL", "CellType", ["STR SST-CHODL", "SST–CHODL", "SST–\nCHODL"]),
    ("E031", "STR PTHLH-PVALB", "CellType", ["STR PTHLH-PVALB", "STR FS PTHLH–PVALB", "STR-PTHLH-PVALB"]),
    ("E032", "STR-BF TAC3-LHX8", "CellType", ["STR-BF TAC3-LHX8"]),
    ("E033", "BF SKOR1 Glut", "CellType", ["BF SKOR1 Glut"]),
    ("E034", "OB FRMD7", "CellType", ["OB FRMD7"]),
    ("E035", "FM GATA3-TCF7L2", "CellType", ["FM GATA3-TCF7L2", "F M GATA3-TCF7L2"]),
    ("E036", "STR Chol", "CellType", ["STR Chol"]),
    ("E037", "STRd Chol", "CellType", ["STRd Chol", "STRd ChAT+"]),
    ("E038", "CN GABA", "CellType", ["CN GABA"]),
    ("E039", "CN CGE GABA", "CellType", ["CN CGE GABA"]),
    ("E040", "CN LGE GABA", "CellType", ["CN LGE GABA"]),
    ("E041", "CN MGE GABA", "CellType", ["CN MGE GABA"]),
    ("E042", "CN Immune GABA", "CellType", ["CN Immune GABA"]),
    ("E043", "Cx GABA", "CellType", ["Cx GABA"]),
    ("E044", "FM GABA", "CellType", ["FM GABA", "F M GABA"]),
    ("E045", "FM Glut", "CellType", ["FM Glut", "F M Glut"]),
    ("E046", "Vascular cells", "CellType", ["Vascular"]),
    ("E047", "Immune cells", "CellType", ["Immune"]),
    ("E048", "Astro-Epen", "CellType", ["Astro-Epen", "Astro–Epen", "astrocyte–ependymal", "astrocytic/ependymal"]),
    ("E049", "OPC-Oligo", "CellType", ["OPC-Oligo", "OPC–Oligo"]),
    ("E050", "committed oligodendrocyte progenitors (COP)", "CellType", ["committed \noligodendrocyte progenitors", "COP"]),
    ("E051", "oligodendrocyte progenitor cells (OPC)", "CellType", ["oligodendrocyte progenitor cells", "OPC"]),
    ("E052", "Oligo PLEKHG1", "CellType", ["Oligo PLEKHG1", "Oligo-PLEKHG1"]),
    ("E053", "Oligo OPALIN", "CellType", ["Oligo OPALIN", "Oligo-OPALIN"]),
    ("E054", "ImOligo", "CellType", ["ImOligo", "immune-associated oligodendrocytes"]),
    ("E055", "WM_Astro", "CellType", ["WM_Astro"]),
    ("E056", "STR_Astro-1", "CellType", ["STR_Astro-1"]),
    ("E057", "STR_Astro-2", "CellType", ["STR_Astro-2"]),
    ("E058", "GP-TH_Astro", "CellType", ["GP-TH_Astro"]),
    ("E059", "ImAstro", "CellType", ["ImAstro"]),
    ("E060", "Ventricle_Astro", "CellType", ["Ventricle_Astro"]),
    ("E061", "astrocytes", "CellType", ["astrocytes", "astrocyte", "Astrocyte"]),
    ("E062", "oligodendrocytes", "CellType", ["oligodendrocytes", "oligodendrocyte"]),
    ("E063", "endothelial cells", "CellType", ["Endo"]),
    ("E064", "pericytes", "CellType", ["Pericyte"]),
    ("E065", "arkypallidal neurons", "CellType", ["arkypallidal \nneurons", "arkypallidal"]),
    ("E066", "prototypic neurons", "CellType", ["prototypic neurons"]),
    ("E067", "GABAergic projection neurons", "CellType", ["GABAergic projection neurons"]),
    ("E068", "GABAergic medium spiny neurons", "CellType", ["GABAergic medium spiny neurons"]),
    ("E069", "Tac2+/TH+ interneurons", "CellType", ["Tac2+/TH+"]),
    ("E070", "M Dopa", "CellType", ["M Dopa"]),
    ("E071", "1163 Astro-TE NN_3", "CellType", ["1163 Astro\n-TE NN_3", "Astro-TE NN_3"]),
    ("E072", "1184 MOL NN_4", "CellType", ["1184 MOL\nNN_4", "MOL NN_4"]),
    ("E073", "0267 STR D1 Gaba_3", "CellType", ["0267 STR D1 Gaba_3"]),
    ("E074", "0268 STR D1 Gaba_4", "CellType", ["0268 STR D1 Gaba_4"]),
    ("E075", "0277 STR D2 Gaba_4_A*", "CellType", ["0277 STR D2 Gaba_4_A*"]),
    ("E076", "0277 STR D2 Gaba_4_B*", "CellType", ["0277 STR D2 Gaba_4_B*"]),
    ("E077", "1193 Endo NN_1", "CellType", ["1193 Endo NN_1"]),
    ("E078", "0980 STR D2 Gaba_4", "CellType", ["0980 STR D2 Gaba_4"]),
    ("E079", "0277 STR D2 Gaba_4", "CellType", ["0277 STR D2 Gaba_4"]),
    ("E080", "0274 STR D2 Gaba_1", "CellType", ["0274 STR D2 Gaba_1"]),
    ("E081", "0275 STR D2 Gaba_2", "CellType", ["0275 STR D2 Gaba_2"]),
    ("E082", "0276 STR D2 Gaba_3", "CellType", ["0276 STR D2 Gaba_3"]),
    ("E083", "0278 STR D2 Gaba_5", "CellType", ["0278 STR D2 Gaba_5"]),
    ("E084", "0279 STR D2 Gaba_6", "CellType", ["0279 STR D2 Gaba_6"]),
    ("E085", "0281 STR D1 Sema5a Gaba_1", "CellType", ["0281 STR D1 Sema5a Gaba_1"]),
    ("E086", "0282 STR D1 Sema5a Gaba_2", "CellType", ["0282 STR D1 Sema5a Gaba_2"]),
    ("E087", "0283 STR D1 Sema5a Gaba_3", "CellType", ["0283 STR D1 Sema5a Gaba_3"]),
    ("E088", "0284 STR D1 Sema5a Gaba_4", "CellType", ["0284 STR D1 Sema5a Gaba_4"]),
    ("E089", "0285 STR-PAL Chst9 Gaba_1", "CellType", ["0285 STR-PAL Chst9 Gaba_1"]),
    ("E090", "0286 STR-PAL Chst9 Gaba_2", "CellType", ["0286 STR-PAL Chst9 Gaba_2"]),
    ("E091", "0287 STR-PAL Chst9 Gaba_3", "CellType", ["0287 STR-PAL Chst9 Gaba_3"]),
    ("E092", "0288 STR-PAL Chst9 Gaba_4", "CellType", ["0288 STR-PAL Chst9 Gaba_4"]),
    ("E093", "0269 STR D1 Gaba_5", "CellType", ["0269 STR D1 Gaba_5"]),
    ("E094", "0270 STR D1 Gaba_6", "CellType", ["0270 STR D1 Gaba_6"]),
    ("E095", "0265 STR D1 Gaba_1", "CellType", ["0265 STR D1 Gaba_1"]),
    ("E096", "0266 STR D1 Gaba_2", "CellType", ["0266 STR D1 Gaba_2"]),
    ("E097", "0272 STR D1 Gaba_8", "CellType", ["0272 STR D1 Gaba_8"]),
    ("E098", "0262 OT D3 Folh1 Gaba_1", "CellType", ["0262 OT D3 Folh1 Gaba_1"]),
    ("E099", "0263 OT D3 Folh1 Gaba_2", "CellType", ["0263 OT D3 Folh1 Gaba_2"]),
    ("E100", "0264 OT D3 Folh1 Gaba_3", "CellType", ["0264 OT D3 Folh1 Gaba_3"]),
    # ============ GENES ============
    ("E101", "DRD1", "Gene", ["DRD1", "dopamine receptor D1"]),
    ("E102", "DRD2", "Gene", ["DRD2", "dopamine receptor D2"]),
    ("E103", "TAC1", "Gene", ["TAC1", "tachykinin precursor 1"]),
    ("E104", "PENK", "Gene", ["PENK", "proenkephalin"]),
    ("E105", "PDYN", "Gene", ["PDYN", "prodynorphin"]),
    ("E106", "CHAT", "Gene", ["CHAT", "choline acetyltransferase"]),
    ("E107", "PVALB", "Gene", ["PVALB", "parvalbumin"]),
    ("E108", "SST", "Gene", ["SST", "somatostatin"]),
    ("E109", "NPY", "Gene", ["NPY", "neuropeptide Y"]),
    ("E110", "TH", "Gene", ["TH", "tyrosine hydroxylase"]),
    ("E111", "LHX6", "Gene", ["LHX6", "LIM homeobox 6"]),
    ("E112", "NKX2-1", "Gene", ["NKX2-1", "NK2 homeobox 1"]),
    ("E113", "NPAS1", "Gene", ["NPAS1", "neuronal PAS domain protein 1"]),
    ("E114", "FOXP2", "Gene", ["FOXP2", "forkhead box protein P2"]),
    ("E115", "AQP4", "Gene", ["AQP4", "aquaporin 4"]),
    ("E116", "AQP1", "Gene", ["AQP1", "aquaporin 1"]),
    ("E117", "SLC6A11", "Gene", ["SLC6A11", "GAT-3"]),
    ("E118", "CHI3L1", "Gene", ["CHI3L1", "chitinase 3-like 1"]),
    ("E119", "ADGRV1", "Gene", ["ADGRV1"]),
    ("E120", "OPALIN", "Gene", ["OPALIN"]),
    ("E121", "PLEKHG1", "Gene", ["PLEKHG1"]),
    ("E122", "RELN", "Gene", ["RELN"]),
    ("E123", "EBF1", "Gene", ["EBF1"]),
    ("E124", "SLIT1", "Gene", ["SLIT1"]),
    ("E125", "SLIT2", "Gene", ["SLIT2"]),
    ("E126", "SEMA3E", "Gene", ["SEMA3E"]),
    ("E127", "SEMA5A", "Gene", ["SEMA5A"]),
    ("E128", "KIRREL3", "Gene", ["KIRREL3"]),
    ("E129", "TAC3", "Gene", ["TAC3"]),
    ("E130", "PLPP4", "Gene", ["PLPP4"]),
    ("E131", "GBX1", "Gene", ["GBX1"]),
    ("E132", "SOX6", "Gene", ["SOX6"]),
    ("E133", "CTXND1", "Gene", ["CTXND1"]),
    ("E134", "MEIS2", "Gene", ["MEIS2"]),
    ("E135", "GATA3", "Gene", ["GATA3"]),
    ("E136", "TCF7L2", "Gene", ["TCF7L2"]),
    ("E137", "ZNF385B", "Gene", ["ZNF385B"]),
    ("E138", "ROBO2", "Gene", ["ROBO2"]),
    ("E139", "EGR1", "Gene", ["EGR1"]),
    ("E140", "SCG2", "Gene", ["SCG2"]),
    ("E141", "CALY", "Gene", ["CALY"]),
    ("E142", "HSPA6", "Gene", ["HSPA6"]),
    ("E143", "DNAJB1", "Gene", ["DNAJB1"]),
    ("E144", "PDE10A", "Gene", ["PDE10A"]),
    ("E145", "NRGN", "Gene", ["NRGN"]),
    ("E146", "NNAT", "Gene", ["NNAT"]),
    ("E147", "CRYM", "Gene", ["CRYM"]),
    ("E148", "RAP1GAP", "Gene", ["RAP1GAP"]),
    ("E149", "LYPD6", "Gene", ["LYPD6"]),
    ("E150", "RSPO2", "Gene", ["RSPO2"]),
    ("E151", "ADARB2", "Gene", ["ADARB2"]),
    ("E152", "CHODL", "Gene", ["CHODL"]),
    ("E153", "PTHLH", "Gene", ["PTHLH"]),
    ("E154", "LHX8", "Gene", ["LHX8"]),
    ("E155", "SKOR1", "Gene", ["SKOR1"]),
    ("E156", "FRMD7", "Gene", ["FRMD7"]),
    ("E157", "CXCL14", "Gene", ["CXCL14"]),
    ("E158", "BCAS1", "Gene", ["BCAS1"]),
    ("E159", "MATN2", "Gene", ["MATN2"]),
    ("E160", "KCNK10", "Gene", ["KCNK10"]),
    ("E161", "ERBIN", "Gene", ["ERBIN"]),
    ("E162", "CDH23", "Gene", ["CDH23"]),
    ("E163", "HHIP", "Gene", ["HHIP"]),
    ("E164", "PTK2", "Gene", ["PTK2"]),
    ("E165", "PTGDS", "Gene", ["PTGDS"]),
    ("E166", "LPAR1", "Gene", ["LPAR1"]),
    ("E167", "MOBP", "Gene", ["MOBP"]),
    ("E168", "NTNG2", "Gene", ["NTNG2"]),
    ("E169", "SLC5A11", "Gene", ["SLC5A11"]),
    ("E170", "ATP10B", "Gene", ["ATP10B"]),
    ("E171", "ST18", "Gene", ["ST18"]),
    ("E172", "MBP", "Gene", ["MBP"]),
    ("E173", "CDK18", "Gene", ["CDK18"]),
    ("E174", "CPXM2", "Gene", ["CPXM2"]),
    ("E175", "FMNL2", "Gene", ["FMNL2"]),
    ("E176", "SYNJ2", "Gene", ["SYNJ2"]),
    ("E177", "CCK", "Gene", ["CCK"]),
    ("E178", "CHRM3", "Gene", ["CHRM3"]),
    ("E179", "RASD2", "Gene", ["RASD2"]),
    ("E180", "GPR88", "Gene", ["GPR88"]),
    ("E181", "CNR1", "Gene", ["CNR1"]),
    ("E182", "HPCA", "Gene", ["HPCA"]),
    ("E183", "SPOCK1", "Gene", ["SPOCK1"]),
    ("E184", "SLC24A2", "Gene", ["SLC24A2"]),
    ("E185", "SEMA3A", "Gene", ["SEMA3A"]),
    ("E186", "KCNIP4", "Gene", ["KCNIP4"]),
    ("E187", "RBFOX1", "Gene", ["RBFOX1"]),
    ("E188", "PCSK1N", "Gene", ["PCSK1N"]),
    ("E189", "GALNTL6", "Gene", ["GALNTL6"]),
    ("E190", "LSAMP", "Gene", ["LSAMP"]),
    ("E191", "SYNPR", "Gene", ["SYNPR"]),
    ("E192", "HTR2C", "Gene", ["HTR2C"]),
    ("E193", "dynorphin", "Gene", ["dynorphin"]),
    ("E194", "enkephalin", "Gene", ["enkephalin"]),
    ("E195", "Folh1", "Gene", ["Folh1"]),
    ("E196", "Chst9", "Gene", ["Chst9"]),
    # ============ BRAIN REGIONS / ANATOMY ============
    ("E201", "basal ganglia", "BrainRegion", ["basal ganglia", "Basal ganglia"]),
    ("E202", "striatum", "BrainRegion", ["striatum", "Striatum"]),
    ("E203", "caudate nucleus", "BrainRegion", ["caudate nucleus", "Caudate", "caudate"]),
    ("E204", "putamen", "BrainRegion", ["putamen", "Putamen"]),
    ("E205", "nucleus accumbens", "BrainRegion", ["nucleus accumbens", "NAc"]),
    ("E206", "NAc shell", "BrainRegion", ["NAc shell", "NAc_shell"]),
    ("E207", "NAc core", "BrainRegion", ["NAc core", "NAc_core"]),
    ("E208", "globus pallidus", "BrainRegion", ["globus pallidus", "globus\npallidus"]),
    ("E209", "external globus pallidus", "BrainRegion", ["external globus pallidus", "GPe"]),
    ("E210", "internal globus pallidus", "BrainRegion", ["internal globus pallidus", "GPi"]),
    ("E211", "internal capsule", "BrainRegion", ["internal capsule"]),
    ("E212", "striosome", "BrainRegion", ["striosome", "Striosome", "striosomes"]),
    ("E213", "matrix compartment", "BrainRegion", ["matrix compartment"]),
    ("E214", "dorsal striatum", "BrainRegion", ["dorsal striatum", "STRd"]),
    ("E215", "ventral striatum", "BrainRegion", ["STRv"]),
    ("E216", "white matter", "BrainRegion", ["white matter", "White_matter"]),
    ("E217", "striatopallidal fiber tracts", "BrainRegion", ["striatopallidal fiber tracts", "striatopallidal fiber bundles"]),
    ("E218", "substantia nigra pars reticulata", "BrainRegion", ["substantia nigra pars reticulata"]),
    ("E219", "anterior commissure", "BrainRegion", ["anterior\ncommissure", "anterior_commissure"]),
    ("E220", "ependymal zone", "BrainRegion", ["Ependymal_zone"]),
    ("E221", "thalamus", "BrainRegion", ["Thalamus", "THM"]),
    ("E222", "BNST", "BrainRegion", ["BNST"]),
    ("E223", "olfactory area", "BrainRegion", ["Olfactory_area"]),
    ("E224", "prefrontal cortex", "BrainRegion", ["prefrontal\ncortex", "prefrontal"]),
    ("E225", "cerebral cortex", "BrainRegion", ["cortex", "cortical"]),
    ("E226", "cerebral nuclei", "BrainRegion", ["cerebral nuclei"]),
    ("E227", "caudoputamen", "BrainRegion", ["caudoputamen"]),
    ("E228", "pallidum", "BrainRegion", ["pallidum"]),
    # ============ TECHNOLOGIES / METHODS ============
    ("E301", "MERFISH+", "Technology", ["MERFISH+"]),
    ("E302", "MERFISH", "Technology", ["MERFISH", "Multiplexed Error-Robust Fluorescence In Situ Hybridization"]),
    ("E303", "Stereo-seq", "Technology", ["Stereo-seq", "Spatio-Temporal Enhanced Resolution Omics-sequencing"]),
    ("E304", "snRNA-seq", "Technology", ["snRNA-seq"]),
    ("E305", "single-cell RNA sequencing", "Technology", ["single-cell RNA sequencing"]),
    ("E306", "fluorescent in situ hybridization", "Technology", ["fluorescent in situ \nhybridization", "FISH"]),
    ("E307", "next-generation sequencing", "Technology", ["next-generation sequencing", "NGS"]),
    ("E308", "smFISH", "Technology", ["smFISH"]),
    ("E309", "UMAP", "Algorithm", ["UMAP", "Uniform Manifold Approximation and Projection"]),
    ("E310", "Principal Component Analysis", "Algorithm", ["Principal Component Analysis", "PCA"]),
    ("E311", "DNA nanoball", "Technology", ["DNA nanoball", "DNB"]),
    ("E312", "in vitro transcription", "Technology", ["in-vitro transcription", "IVT"]),
    ("E313", "reverse transcription", "Technology", ["reverse transcription"]),
    ("E314", "cryosectioning", "Method", ["cryostat sections", "Cryosections", "cryostat"]),
    ("E315", "cellular community analysis", "Method", ["cellular community analysis"]),
    ("E316", "Leiden clustering", "Algorithm", ["Leiden clustering", "Leiden algorithm", "Leiden"]),
    ("E317", "K-nearest neighbor graph", "Algorithm", ["K-nearest neighbor graph", "KNN graph"]),
    ("E318", "watershed algorithm", "Algorithm", ["watershed \nalgorithm"]),
    ("E319", "CLAHE", "Algorithm", ["contrast limited adaptive histogram equalization", "CLAHE"]),
    ("E320", "BCDU-Net", "Algorithm", ["BCDU-Net"]),
    ("E321", "Wiener algorithm", "Algorithm", ["Wiener algorithm", "Wiener’s algorithm"]),
    ("E322", "Pearson correlation", "Method", ["Pearson correlation", "Pearsons correlation"]),
    ("E323", "Wilcoxon rank-sum test", "Method", ["Wilcoxon rank-sum test", "Wilcoxon rank sum"]),
    ("E324", "Cochran-Mantel-Haenszel test", "Method", ["Cochran-Mantel-Haenszel statistics", "Cochran–Mantel–Haenszel test"]),
    ("E325", "Benjamini-Hochberg method", "Method", ["Benjamini–Hochberg\nmethod"]),
    ("E326", "Bonferroni method", "Method", ["Bonferroni method"]),
    ("E327", "LOWESS regression", "Method", ["lowess regression"]),
    ("E328", "DBSCAN", "Algorithm", ["DBSCAN"]),
    ("E329", "3D Delaunay triangulation", "Algorithm", ["3D Delaunay triangulation"]),
    ("E330", "harmony integration", "Method", ["harmony integration"]),
    ("E331", "phase cross-correlation", "Method", ["phase cross-correlation"]),
    ("E332", "permutation test", "Method", ["permutation test"]),
    ("E333", "gene ontology enrichment analysis", "Method", ["gene ontology enrichment analysis", "Gene Ontology enrichment analysis"]),
    ("E334", "Metropolis Hastings optimization", "Algorithm", ["Metropolis Hastings optimization algorithm"]),
    ("E335", "set cover algorithm", "Algorithm", ["set cover algorithm"]),
    ("E336", "chi-square test", "Method", ["chi-square"]),
    ("E337", "MapMyCells", "Software", ["MapMyCells", "MapMyCell"]),
    # ============ SOFTWARE ============
    ("E401", "Scanpy", "Software", ["Scanpy package", "Scanpy", "scanpy"]),
    ("E402", "scikit-learn", "Software", ["scikit-learn"]),
    ("E403", "SciPy", "Software", ["SciPy"]),
    ("E404", "NumPy", "Software", ["NumPy"]),
    ("E405", "OpenCV", "Software", ["OpenCV", "Opencv"]),
    ("E406", "statsmodel", "Software", ["statsmodel"]),
    ("E407", "pandas", "Software", ["pandas package"]),
    ("E408", "pyvista", "Software", ["pyvista package", "pyvista"]),
    ("E409", "Cellpose", "Software", ["Cellpose"]),
    ("E410", "STAR aligner", "Software", ["STAR aligner"]),
    ("E411", "storm-control", "Software", ["storm-control", "Storm-control"]),
    ("E412", "SAW", "Software", ["SAW", "Stereo-seq Analysis \nWorkflow", "Stereo-seq Analysis\nWorkflow"]),
    ("E413", "cell_type_mapper", "Software", ["cell_type_mapper"]),
    ("E414", "gget", "Software", ["gget package"]),
    ("E415", "goatools", "Software", ["goatools package"]),
    ("E416", "GODag", "Software", ["GODag"]),
    ("E417", "sdeconv", "Software", ["sdeconv package"]),
    ("E418", "StereoMap ImageQC", "Software", ["StereoMap ImageQC", "ImageQC"]),
    # ============ DATASETS / ATLASES / DATABASES ============
    ("E501", "Allen Human Brain Atlas", "Dataset", ["Allen Human Brain Atlas", "Allen human Brain atlas"]),
    ("E502", "Allen Institute Mammalian Basal Ganglia Consensus Cell Type Atlas", "Dataset", ["Allen Institute Mammalian Basal Ganglia Consensus Cell Type Atlas", "Basal Ganglia Consensus Cell Type Atlas"]),
    ("E503", "whole mouse brain MERFISH dataset", "Dataset", ["whole-mouse-brain MERFISH dataset"]),
    ("E504", "BICAN", "Dataset", ["BICAN"]),
    ("E505", "BICAN brain bank", "Resource", ["BICAN brain bank", "BICAN Brain Bank"]),
    ("E506", "Mouse Genome Informatics database", "Database", ["Mouse Genome informatics (MGI) database", "MGI"]),
    ("E507", "GRCh38", "Dataset", ["GRCh38"]),
    ("E508", "C57BL6J-638850.39 - 50", "Dataset", ["C57BL6J-638850.39 - 50"]),
    ("E509", "Brain Image Library", "Resource", ["Brain Image Library", "Brain Image \nLibrary (BIL)", "BIL"]),
    ("E510", "NeMO Archive", "Resource", ["NeMOarchive", "NeMO Archive"]),
    ("E511", "Ensembl", "Database", ["Ensembl"]),
    ("E512", "Cross-species Basal ganglion cell type taxonomy", "Dataset", ["Cross-species Basal ganglion cell\ntype taxonomy"]),
    # ============ DISEASES ============
    ("E601", "Parkinson's disease", "Disease", ["Parkinson’s disease"]),
    ("E602", "Huntington's disease", "Disease", ["Huntington’s disease"]),
    ("E603", "movement disorders", "Disease", ["movement disorders"]),
    ("E604", "neuropsychiatric disorders", "Disease", ["neuropsychiatric disorders", "neuropsychiatric conditions"]),
    ("E605", "neurodegenerative disease", "Disease", ["neurodegenerative disease", "neurodegenerative pathology"]),
    # ============ SPECIES ============
    ("E701", "human", "Species", ["human", "humans", "Human"]),
    ("E702", "mouse", "Species", ["mouse", "mice", "Mouse"]),
    ("E703", "non-human primate", "Species", ["non-human primate", "non-human primates", "nonhuman primates"]),
    ("E704", "macaque", "Species", ["macaques"]),
    ("E705", "C57BL/6J", "Species", ["C57BL6J"]),
    ("E706", "rodent", "Species", ["rodents", "rodent"]),
    ("E707", "monkey", "Species", ["monkey"]),
    # ============ REAGENTS ============
    ("E801", "isopentane", "Reagent", ["Isopentane", "isopentane"]),
    ("E802", "methanol", "Reagent", ["methanol", "Methanol"]),
    ("E803", "ethanol", "Reagent", ["Ethanol", "ethanol"]),
    ("E804", "formamide", "Reagent", ["Formamide", "formamide"]),
    ("E805", "Triton X-100", "Reagent", ["Triton X-100"]),
    ("E806", "Trolox", "Reagent", ["Trolox"]),
    ("E807", "Poly-D-lysine", "Reagent", ["Poly-D-lysine", "Poly-D-Lysine", "PDL"]),
    ("E808", "paraformaldehyde", "Reagent", ["PFA", "paraformaldehyde"]),
    ("E809", "DAPI", "Reagent", ["DAPI"]),
    ("E810", "SDS", "Reagent", ["SDS"]),
    ("E811", "TEMED", "Reagent", ["TEMED"]),
    ("E812", "catalase", "Reagent", ["Catalase"]),
    ("E813", "glucose oxidase", "Reagent", ["Glucose Oxidase"]),
    ("E814", "Maxima H Minus Reverse Transcriptase", "Reagent", ["Maxima H Minus  \nReverse Transcriptase"]),
    ("E815", "Phusion High-Fidelity DNA Polymerase", "Reagent", ["Phusion High-Fidelity DNA \nPolymerase", "Phusion Plus PCR Master Mix"]),
    ("E816", "HiScribe T7 RNA Synthesis Kit", "Reagent", ["HiScribe T7 ARCA mRNA kit"]),
    ("E817", "RNase Inhibitor", "Reagent", ["RNase Inhibitor", "RNase inhibitor"]),
    ("E818", "dextran sulfate", "Reagent", ["Dextran Sulfate", "dextran sulfate"]),
    ("E819", "ammonium persulfate", "Reagent", ["Ammonium persulfate"]),
    ("E820", "Qubit dsDNA HS Assay Kit", "Reagent", ["Qubit dsDNA HS Assay Kit"]),
    ("E821", "Qubit ssDNA Assay Kit", "Reagent", ["Qubit™ ssDNA Assay Kit"]),
    ("E822", "Cy3", "Reagent", ["Cy3"]),
    ("E823", "Cy5", "Reagent", ["Cy5"]),
    ("E824", "OCT embedding medium", "Reagent", ["OCT \nembedding medium", "OCT"]),
    ("E825", "proteinase K", "Reagent", ["proteinase K"]),
    ("E826", "Alexa 750", "Reagent", ["5Alex750N/3AlexF750N"]),
    ("E827", "Stereo-seq chip", "Reagent", ["Stereo-seq chips", "Stereo-seq chip"]),
    # ============ EQUIPMENT ============
    ("E901", "Echo Revolution microscope", "Equipment", ["Echo Revolution \nmicroscope"]),
    ("E902", "MGI DNBSEQ-T7", "Equipment", ["MGI DNBSEQ-T7", "DNBSEQ™ T7 platform"]),
    ("E903", "Leica CM1850 cryostat", "Equipment", ["Leica \nCM1850 cryostat", "Leica CM1850"]),
    ("E904", "ASI microscope body", "Equipment", ["ASI microscope body"]),
    ("E905", "Nikon CFI Plan Apo 60X Lambda D", "Equipment", ["Nikon CFI Plan Apo 60X Lambda D"]),
    ("E906", "Vizgen photobleacher", "Equipment", ["Vizgen photobleacher"]),
    ("E907", "Agilent TapeStation", "Equipment", ["Agilent TapeStation"]),
    # ============ ORGANIZATIONS ============
    ("E1001", "Allen Institute", "Organization", ["Allen Institute", "Allen institute"]),
    ("E1002", "University of California, Irvine", "Organization", ["University of California, Irvine", "UCI"]),
    ("E1003", "BRAIN Initiative", "Organization", ["BRAIN Initiative"]),
    ("E1004", "Salk Institute", "Organization", ["Salk Institute"]),
    ("E1005", "Twist Bioscience", "Organization", ["Twist Bioscience", "Twist Biosciences"]),
    ("E1006", "Integrated DNA Technologies", "Organization", ["IDT"]),
    ("E1007", "Sigma-Aldrich", "Organization", ["Sigma-Aldrich", "SigmaAldrich"]),
    ("E1008", "Thermo Fisher Scientific", "Organization", ["Thermo Fisher Scientific"]),
    ("E1009", "Complete Genomics", "Organization", ["Complete Genomics"]),
    ("E1010", "STOmics", "Organization", ["STOmics"]),
    ("E1011", "New England Biolabs", "Organization", ["New England Biolabs", "NEB"]),
    ("E1012", "Zymo Research", "Organization", ["Zymo Research"]),
    ("E1013", "Invitrogen", "Organization", ["Invitrogen"]),
    ("E1014", "Agilent", "Organization", ["Agilent"]),
    ("E1016", "PacGenomics", "Organization", ["PacGenomics"]),
    ("E1017", "Vizgen", "Organization", ["Vizgen"]),
    ("E1018", "CellPath", "Organization", ["CellPath"]),
    ("E1019", "Harvard University Zhuang Lab", "Organization", ["Harvard University Zhuang \nLab"]),
    ("E1020", "Discover Echo", "Organization", ["Discover Echo"]),
    # ============ DONOR SAMPLES ============
    ("E1101", "Case UCI-2724", "DonorSample", ["Case#UCI-2724", "#2724"]),
    ("E1102", "Case UCI-3924", "DonorSample", ["Case#UCI-3924", "#3924"]),
    ("E1103", "Case UCI-1311", "DonorSample", ["Case#UCI-1311", "#1311"]),
    ("E1104", "Case UCI-5129", "DonorSample", ["Case#UCI-5129", "#5129"]),
    # ============ METRICS ============
    ("E1201", "RNA Integrity Number", "Metric", ["RNA Integrity Number", "RIN"]),
    ("E1202", "postmortem interval", "Metric", ["postmortem interval (PMI)", "PMI"]),
    ("E1203", "odds ratio", "Metric", ["odds ratio", "Odds ratio", "odds-ratio"]),
    ("E1204", "p-value", "Metric", ["p-value"]),
    ("E1205", "FDR", "Metric", ["FDR"]),
    ("E1206", "Hamming distance", "Metric", ["hamming distance"]),
]

# Verify and drop missing surface forms
entity_dict = {}
dropped = []
for eid, etext, etype, sforms in raw_entities:
    valid = [sf for sf in sforms if sf in SRC]
    invalid = [sf for sf in sforms if sf not in SRC]
    for sf in invalid:
        dropped.append((eid, sf))
    if not valid:
        print(f"WARNING: entity {eid} ({etext}) has NO valid surface forms; dropping")
        continue
    entity_dict[eid] = {
        "entity_id": eid,
        "entity_text": etext,
        "entity_type": etype,
        "surface_forms": valid,
        "extraction_round": 1,
    }

print(f"Total kept entities: {len(entity_dict)}")
print(f"Dropped surface forms: {len(dropped)}")
for d in dropped[:30]:
    print(f"  DROP: {d}")

Path("agent1_entities_round1.json").write_text(json.dumps(entity_dict, indent=2))

# Build masked text
all_forms = []
for eid, ent in entity_dict.items():
    all_forms.extend(ent["surface_forms"])
all_forms_sorted = sorted(set(all_forms), key=lambda x: -len(x))

masked = SRC
for sf in all_forms_sorted:
    repl = "".join("*" if c != "\n" else "\n" for c in sf)
    masked = masked.replace(sf, repl)

Path("multiscale_spatial_transcriptomic_masked_round1.txt").write_text(masked)
print(f"\nMasked round 1 written. Source chars: {len(SRC)}, asterisks added: {masked.count('*') - SRC.count('*')}")
