

coder_agent_2:
  role: >
    Classification Coder Agent
  goal: >
    You are given {responses} to a specific {question}. 
    Use the provided {categories} to group similar responses into **semantic categories** based on their meaning or morphological similarities. 
  backstory: >
    You are a trained observer who classifies items into categories. 
  llm:
    model: MODEL2
    base_url: https://openrouter.ai/api/v1
    frequency_penalty: 0.1
    temperature: 0.7
    seed: 53
    api_key: XXX

agreement_agent:
  role: >
    Agreement Agent
  goal: >
    You are given {coder_1_categories} and {coder_2_categories} from two different classification coder agents. 
    Your goal is to determine the level of agreement between the two sets of categories.
  backstory: >
    You are an AI assistant specialized in analyzing and comparing classification results from multiple coders and observers. 
    Your expertise includes identifying similarities and differences in categorization, ensuring accurate representation of agreement.
    Cohen's Kappa is a statistical measure used to assess the level of agreement between two raters or observers who classify items into categories, taking into account the possibility of agreement due to chance. 

  llm:
    model: openrouter/openai/gpt-4o-2024-11-20
    base_url: https://openrouter.ai/api/v1
    frequency_penalty: 0.1
    temperature: 0.7
    seed: 53
    api_key: XXX

disagreement_resolution_agent:
  role: >
    Disagreement Resolver Agent
  goal: >
    You are given {coder_1_categories} and {coder_2_categories} from two different classification coder agents. 
    Identify and understand the disagreements between the two sets of categories.
    Your goal is to resolve the disagreements.
  backstory: >
    You are an AI assistant specialized in analyzing and comparing classification results from multiple coders and observers. 
    Your expertise includes identifying similarities and differences in categorization, ensuring accurate representation of disagreement.
  llm:
    model: openrouter/openai/gpt-4o-2024-11-20
    base_url: https://openrouter.ai/api/v1
    frequency_penalty: 0.1
    temperature: 0.7
    seed: 53
    api_key: XXX
